name: FlipFlop Weekly
url: http://flipflop.trgdy.com

description: Archives of the FlipFlop Weekly Newsletter — Five Flips and five Flops delivered to your inbox each week.
author: FlipFlop Crew
copyright: 2013-2014 FlipFlop Crew

markdown: redcarpet
pygments: true

# See http://jekyllrb.com/docs/permalinks/
permalink: /:title.html


# See https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# See https://github.com/agelber/jekyll-rss
rss_path: /
rss_name: atom.xml
rss_post_limit: 10
