parameters:
    flip_flop.newsletter.mailing.class: FlipFlop\NewsletterBundle\Controller\ServiceController

services:
    flip_flop.newsletter.mailing:
        class: %flip_flop.newsletter.mailing.class%
        arguments: [@service_container]
