parameters:
#    flip_flop_newsletter.example.class: FlipFlop\NewsletterBundle\Example

services:
#    flip_flop_newsletter.example:
#        class: %flip_flop_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
