security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FlipFlop\AuthBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: FlipFlop\AuthBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: flipflop_site_logincheck
                login_path: flipflop_site_loginpage
                default_target_path: /
            logout:
                path: flipflop_site_logout
                target: /
                invalidate_session: false