flip_flop_auth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FlipFlopAuthBundle:Default:index }

flipflop_entity_crud_user:
    resource: "@FlipFlopAuthBundle/Resources/config/routing/user.yml"
    prefix:   /user
