parameters:
#    flip_flop_auth.example.class: FlipFlop\AuthBundle\Example

services:
#    flip_flop_auth.example:
#        class: %flip_flop_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
